theme: jekyll-theme-minimal
title: Un dolce deliro
description: "Ein Musiktheaterstück frei nach Joseph Haydns «L’isola disabitata» und mit Singer/Songwriter-Eigenkompositionen\n\nBachelorprojekt von Aline Dätwyler an der Hochschule Luzern – Musik"
