theme: jekyll-theme-minimal
title: Un dolce deliro
description: <p>Ein Musiktheaterstück frei nach Joseph Haydns «L’isola disabitata» und mit Singer/Songwriter-Eigenkompositionen</p><p>Bachelorprojekt von Aline Dätwyler an der Hochschule Luzern – Musik</p><p><a href="img/flyer_big.jpg" data-fancybox="images"><img src="img/flyer_small.jpg" alt=""/></a></p>
lang: de-CH
